# Notes for humans and agents alike.
#
# This example is purely documentation,
# and is not referenced anywhere in the configuration.
#
# ALL /path/to/flake/modules/**/*.nix files are automatically
# discovered and exposed to the flake via;
#
#     inputs.snowfall-lib.mkFlake {
#       src = ./.;
#     };
#
#   - modules/nixos/**/default.nix for system modules.
#   - modules/home/**/default.nix for home-manager modules.
#   - modules/**/*.nix for in-module imports, like themes, or scripts.
#
# ANY files untracked by the repo associated with this config, are *invisible*
# to snowfall-lib, and will never be discovered. you need to run
# `git add /path/to/file(s)/(changed|added|removed)`

{
  config,
  lib,
  pkgs,
  # inputs, only needed for flake related modules
  ...
}:

# Bring lib.custom helpers into scope
with lib;
with lib.custom;
# lib.custom gets generated by snowfall-lib automatically.
# All `lib/<name>/default.nix` files are automatically discovered,
# merged into one attrset, and exposed as lib.custom via the
# `snowfall.namespace = "custom"` option in flake.nix.
#

# Define module level variables
let
  cfg = config.apps.term.kitty;
in

{

  # Module options.
  #   We DO NOT define thematic changes here. User customization happens
  #   inside the config block below, not in the home/system/module config where we
  #   enable <module>.
  options.apps.term.kitty = with types; {
    enable = mkBoolOpt false "Enable Kitty";
  };

  # Config options.
  config = mkIf cfg.enable {
    programs.kitty = {
      enable = true;
      package = pkgs.kitty;
      settings = {

        # we exposed the ${colors} attrset with `with lib.custom;`
        # earlier in the module, so all we need to do is pick one of
        # the colours with ${colors.<color>.hex}
        color0 = "${colors.surface1.hex}";
        color8 = "${colors.surface2.hex}";
        color1 = "${colors.red.hex}";
        color9 = "${colors.red.hex}";
        color2 = "${colors.green.hex}";
        color10 = "${colors.green.hex}";
        color3 = "${colors.yellow.hex}";
        color11 = "${colors.yellow.hex}";
        color4 = "${colors.blue.hex}";
        color12 = "${colors.blue.hex}";
        color5 = "${colors.pink.hex}";
        color13 = "${colors.pink.hex}";
        color6 = "${colors.teal.hex}";
        color14 = "${colors.teal.hex}";
        color7 = "${colors.subtext1.hex}";
        color15 = "${colors.subtext0.hex}";

        # if importing from elsewhere in the config
        # `(import ./lib-theme-import-example.nix) { inherit lib; };`
      };

    };
  };

}
