{
  lib,
  pkgs,
  config,
  ...
}:

with lib;
with lib.custom;

let
  srvName = "tekkit2";
  cfg = config.gaming.minecraft.servers.${srvName};
  stateDir = "/var/lib/minecraft-${srvName}";

  # Generates a full server.properties from module options
  serverProperties = ''
    # Tekkit 2 Server - Generated by NixOS
    allow-flight=${if cfg.allowFlight then "true" else "false"}
    allow-nether=true
    broadcast-console-to-ops=true
    difficulty=${toString cfg.difficulty}
    enable-command-block=false
    enable-query=true
    enable-rcon=false
    force-gamemode=false
    gamemode=${toString cfg.gamemode}
    generate-structures=true
    generator-settings=
    hardcore=false
    level-name=${cfg.worldName}
    level-seed=${cfg.seed}
    level-type=${cfg.levelType}
    max-build-height=256
    max-players=${toString cfg.maxPlayers}
    max-tick-time=-1
    max-world-size=29999984
    motd=${cfg.motd}
    network-compression-threshold=256
    online-mode=${if cfg.onlineMode then "true" else "false"}
    op-permission-level=4
    player-idle-timeout=0
    prevent-proxy-connections=false
    pvp=${if cfg.pvp then "true" else "false"}
    query.port=${toString cfg.port}
    resource-pack=
    resource-pack-sha1=
    server-ip=0.0.0.0
    server-port=${toString cfg.port}
    snooper-enabled=true
    spawn-animals=true
    spawn-monsters=true
    spawn-npcs=true
    use-native-transport=true
    view-distance=${toString cfg.viewDistance}
    white-list=${if cfg.whitelist then "true" else "false"}
  '';

  # Graceful-shutdown wrapper using a named pipe (FIFO)
  # ── Fixes ──────────────────────────────────────────────────────────
  # The FIFO is kept open for writing on FD 3 so cat never sees EOF.
  # cat feeds the FIFO into Java's stdin — commands written to the FIFO
  # (by mc-cmd, mc-console, or the stop handler) reach the server.
  wrapperScript = pkgs.writeShellScript "minecraft-${srvName}-wrapper" ''
    set -euo pipefail

    WORK_DIR="${stateDir}"
    JAVA="${pkgs.jdk8}/bin/java"
    JAR="$WORK_DIR/forge-1.12.2-14.23.5.2860.jar"
    MEM="${cfg.memory}"
    JAVA_OPTS="-server -Xmx$MEM -Dfml.queryResult=confirm -Duser.language=en"
    FIFO="$WORK_DIR/.stdin-fifo"

    cd "$WORK_DIR"

    rm -f "$FIFO"
    mkfifo "$FIFO"
    chmod o+w "$FIFO"

    # Start the pipeline FIRST (cat blocks on open-for-read).
    # Then we open the FIFO for writing below, which unblocks cat.
    cat "$FIFO" | $JAVA $JAVA_OPTS -jar "$JAR" nogui &
    PID=$!

    # Now open the FIFO for writing — cat is already waiting to read.
    # FD 3 stays open so cat never sees EOF.
    exec 3>"$FIFO"

    shutdown() {
        echo "stop" > "$FIFO" 2>/dev/null || true
        # Wait as long as Java needs — never force-kill (world corruption risk)
        while kill -0 $PID 2>/dev/null; do
            sleep 1
        done
        exec 3>&-
        rm -f "$FIFO"
        exit 0
    }
    trap shutdown SIGTERM SIGINT

    wait $PID
    EXIT_CODE=$?
    exec 3>&-
    rm -f "$FIFO"
    exit $EXIT_CODE
  '';

  setupScript = pkgs.writeShellScript "minecraft-${srvName}-setup" ''
        set -euo pipefail

        SRC="${cfg.serverSource}"
        DEST="${stateDir}"

        # Copy server files on first run (empty state directory)
        if [ ! -d "$DEST" ] || [ -z "$(ls -A "$DEST" 2>/dev/null)" ]; then
            echo "Minecraft[${srvName}]: Copying server files from $SRC..."
            mkdir -p "$DEST"
            cp -r "$SRC/"* "$DEST/"
            chmod -R u+w "$DEST/"
        fi

        # Accept Minecraft EULA
        if [ ! -f "$DEST/eula.txt" ]; then
            echo "Minecraft[${srvName}]: Accepting EULA..."
            {
                echo "# By setting eula=true you are agreeing to the Minecraft EULA"
                echo "# https://aka.ms/MinecraftEULA"
                echo "eula=true"
            } > "$DEST/eula.txt"
        fi

        # Write a fresh server.properties every time (keeps in sync with config)
        echo "Minecraft[${srvName}]: Writing server.properties..."
        cat > "$DEST/server.properties" << 'PROP'
    ${serverProperties}
    PROP

        chown -R "minecraft-${srvName}:minecraft-${srvName}" "$DEST"
  '';
in

{
  options.gaming.minecraft.servers.${srvName} = with types; {
    enable = mkBoolOpt false "Enable the Tekkit 2 Minecraft server (MC 1.12.2 / Forge).";

    serverSource = mkOption {
      type = str;
      default = "/mnt/nix-data/Games/minecraft/servers/tekkit2";
      example = "/mnt/nix-data/Games/minecraft/servers/tekkit2";
      description = ''
        Absolute path to the extracted Tekkit 2 server files directory.
        Must contain forge-1.12.2-14.23.5.2860.jar, mods/, config/, etc.
      '';
    };

    memory = mkOption {
      type = str;
      default = "3G";
      example = "4G";
      description = "Maximum heap memory (e.g. 2G, 4G, 6G).";
    };

    port = mkOption {
      type = port;
      default = 25565;
      description = "Server port for Minecraft connections.";
    };

    openFirewall = mkOption {
      type = bool;
      default = true;
      description = "Open the server port in the NixOS firewall.";
    };

    motd = mkOption {
      type = str;
      default = "Tekkit 2 Server";
      description = "Message of the day shown in the server list.";
    };

    maxPlayers = mkOption {
      type = ints.positive;
      default = 16;
      description = "Maximum number of players.";
    };

    difficulty = mkOption {
      type = types.enum [
        0
        1
        2
        3
      ];
      default = 2;
      description = "Game difficulty: 0=Peaceful, 1=Easy, 2=Normal, 3=Hard.";
    };

    gamemode = mkOption {
      type = types.enum [
        0
        1
        2
        3
      ];
      default = 0;
      description = "Default gamemode: 0=Survival, 1=Creative, 2=Adventure, 3=Spectator.";
    };

    onlineMode = mkOption {
      type = bool;
      default = false;
      description = ''
        Verify Mojang accounts. Set to false for LAN play so your friend
        can join without a premium Minecraft account.
      '';
    };

    whitelist = mkOption {
      type = bool;
      default = false;
      description = "Enable whitelist. Only whitelisted players can join.";
    };

    pvp = mkOption {
      type = bool;
      default = true;
      description = "Enable player-vs-player combat.";
    };

    allowFlight = mkOption {
      type = bool;
      default = true;
      description = "Allow flight (needed for IC2 jetpacks, etc.).";
    };

    seed = mkOption {
      type = str;
      default = "";
      description = "World seed. Empty = random.";
    };

    worldName = mkOption {
      type = str;
      default = "world";
      description = "Name of the world folder.";
    };

    levelType = mkOption {
      type = str;
      default = "DEFAULT";
      description = "World type: DEFAULT, FLAT, LARGEBIOMES, AMPLIFIED, CUSTOMIZED.";
    };

    viewDistance = mkOption {
      type = ints.between 3 32;
      default = 10;
      description = "Client view distance in chunks.";
    };
  };

  config = mkIf (config.gaming.minecraft.enable && cfg.enable) {

    networking.firewall.allowedTCPPorts = mkIf cfg.openFirewall [ cfg.port ];

    users.users."minecraft-${srvName}" = {
      description = "Minecraft Server - Tekkit 2";
      group = "minecraft-${srvName}";
      isSystemUser = true;
      home = stateDir;
      createHome = true;
    };

    users.groups."minecraft-${srvName}" = { };

    systemd.services."minecraft-${srvName}" = {
      description = "Tekkit 2 Minecraft Server";
      after = [ "network.target" ];
      # wantedBy deliberately omitted — user starts manually via aliases

      preStart = "${setupScript}";

      serviceConfig = {
        ExecStart = "${wrapperScript}";
        User = "minecraft-${srvName}";
        Group = "minecraft-${srvName}";
        Type = "simple";
        TimeoutStopSec = "infinity";
        Restart = "on-failure";
        RestartSec = "5s";
        WorkingDirectory = stateDir;
        StateDirectory = "minecraft-${srvName}";
        StateDirectoryMode = "0755";
        KillMode = "process";
        NoNewPrivileges = true;
        PrivateTmp = true;
      };
    };
  };
}
