# Notes for humans and agents alike.
#
# This example is purely documentation,
# and is not referenced anywhere in the configuration.
#
# ALL /path/to/flake/modules/**/*.nix files are automatically
# discovered and exposed to the flake via;
#
#     inputs.snowfall-lib.mkFlake {
#       src = ./.;
#     };
#
#   - modules/nixos/**/default.nix for system modules.
#   - modules/home/**/default.nix for home-manager modules.
#   - modules/**/*.nix for in-module imports, like themes, or scripts.
#
# ANY files untracked by the repo associated with this config, are *invisible*
# to snowfall-lib, and will never be discovered. you need to `git add /path/to/file(s)/(changed|added|removed)`

{
  config,
  lib,
  pkgs,
  # inputs, only needed for flake related modules
  ...
}:

# Bring lib.custom helpers into scope
with lib;
with lib.custom;
# lib.custom gets generated by snowfall-lib automatically.
# All `lib/<name>/default.nix` files are automatically discovered,
# merged into one attrset, and exposed as lib.custom via the
# `snowfall.namespace = "custom"` option in flake.nix.

# Define module level variables
let
  cfg = config.apps.term.cowsay;
  # system = pkgs.stdenv.hostPlatform.system; only needed for flake/darwin
in

{

  # Module options.
  #   The only thing you should have to set in your config, is
  #   `<module>.enable = true;`
  #   All configuration is handled in the `config` block below, rather
  #   than scattered across (possibly multiple) modules and config files.
  options.apps.term.cowsay = with types; {
    # this could be;
    #   inside ~/builds/homes/x86_64-linux/helios@helios/default.nix
    #     options.apps.term.<programName>
    #     options.apps.helpers.<programName>
    #     options.services.<programName>
    #
    #   inside ~/builds/systems/x86_64-linux/helios/default.nix
    #     options.protocols.wayland
    #     options.services.<serviceName>
    #       Note: Not all modules can be declared with the current convention
    #       - Services like `greetd` run under a bare `config.greetd.enable=true`
    #       instead of `config.services.greetd.enable=true` because they provide something
    #       that conflicts with the intended name.
    #       - greetd provides a `services.greetd`, so we cant name the module that, even though
    #       we want the module inside /path/to/flake/modules/nixos/services/greetd.

    # Force the default boolean to be false.
    enable = mkBoolOpt false "Enable Cowsay";
    # Enable with <module>.enable=true; inside the respective
    # configuration file (systems/**/*.nix, or homes/**/*.nix)
    #
    # - `string = mkStringOpt 10 "Whats the number for";`
    # - `path = mkPathOpt /path/to/thing "Whats the path for";`
  };

  # Config options.
  config = mkIf cfg.enable {
    # This section would be filled with the application specific
    # module options, like `package = `, `settings = `, or `extraConfig = ''...''`
    # or general nix things like `home.packages`, or `environment.variables``

    programs.cowsay = {
      enable = true;
      package = pkgs.cowsay;

      # if importing flake packages;
      # package = inputs.<flake>.packages.${system}.<binary>
    };
  };

}
